server:
  port: 8088

spring:
  application:
    name: msreceta

  datasource:
    url: jdbc:mysql://localhost:3306/msreceta
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka